### ISSUE TITLE
Validation runs #2

### ISSUE THREAD

**Issue by sharanbngr** [sharanbngr/blip#38]
We will now calculate if the orbiting/stationary bayes factors decrease with nside. 

- [x]  Run orbiting and stationary analysis with nside =4 and seeds= 10, 20, 30, 40,50, 60

- [x] Run orbiting and stationary analysis with nside =8 and seeds= 10, 20, 30, 40,50, 60

- [x] Make bayesfactor plots for them both. 

- [x] Try to generate posterior corner plots which plot Omega_0 rather than log(Omega_0)

Unless we are changing them we will use standard settings of fmin = 1e-4, fmax = 2e-2, duration = 2e6, seglen = 5e4, nside = 6, alpha=2/3, omega0 = 4.5e-9, seed=10, fs=0.25, FixSeed=1, mldc=0

- [x] Repeat everything with fmax = 2e-2 with all the other parameters being the same.

**Comment by kuan0020** [comment]
Hey @sharanbngr 

I think by adding this code below 

> post = np.loadtxt(params['out_dir'] + "/post_samples.txt")

 in plotmaker.py will generate a corner plot for Omega0 instead of log10Omega0. Let me know if it's right!

### Change Omega0 from "log10 Omega" back to normal
    for x in range(len(post)):
        post[x][1] = np.power(10,post[x][1])

**Comment by kuan0020** [comment]
And I think because of these lines:
```
   # Adjust axis labels
    for ii in range(npar):
        ax = axes[ii, ii]

        # get the right summary for the parameter ii
        sum_ax = sum_data[parameters[ii]]
        err =  [sum_ax[2] - sum_ax[1], sum_ax[1]- sum_ax[0]]

        if np.abs(sum_ax[1]) <= 1e-3:
            mean_def = '{0:.3e}'.format(sum_ax[1])
            eidx = mean_def.find('e')
            base = float(mean_def[0:eidx])
            exponent = int(mean_def[eidx+1:])
            mean_form = str(base) + ' \\times ' + '10^{' + str(exponent) + '} '
        else:
            mean_form = '{0:.3f}'.format(sum_ax[1])

        if np.abs(err[0]) <= 1e-2:
            err[0] = '{0:.4f}'.format(err[0])
        else:
            err[0] = '{0:.2f}'.format(err[0])

        if np.abs(err[1]) <= 1e-2:
            err[1] = '{0:.4f}'.format(err[1])
        else:
            err[1] = '{0:.2f}'.format(err[1])

        label =  parameters[ii][:-1] + ' = ' + mean_form + '^{+' + err[0] + '}_{-' + err[1] + '}$'

        ax.set_title(label, {'fontsize':23}, loc='left')
```
It gave me this latex error that prevented me from plotting corner plots:
```
python3 run_blip.py params.ini
Simulating instrumental noise ...
 Adding sgwb signal ...
Calculating fourier spectra... 
Diagnostic spectra plot made in ./o_aet_1e_10_noLog2/diag_psd.png
Doing an isotropic stochastic analysis...
npar = 4
iter: 7542 | +500 | bound: 80 | nc: 1 | ncall: 160920 | eff(%):  4.998 | loglstar:   -inf < 7010623.206 <    inf | logz: 7010608.900 +/-  0.225 | dlogz:  0.001 >  0.500                                                                                      
 Making posterior Plots ...
Traceback (most recent call last):
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/home/tommy/.cache/matplotlib/tex.cache/0dfca64bb48e87b7cdbc55a9f95e977e.tex']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_blip.py", line 471, in <module>
    blip(sys.argv[1])
  File "run_blip.py", line 464, in blip
    plotmaker(params, parameters, npar)
  File "/home/tommy/lisaenv/blip/tools/plotmaker.py", line 94, in plotmaker
    plt.savefig(params['out_dir'] + 'corners.png', dpi=150)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 527, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    self._update_title_position(renderer)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2556, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/text.py", line 298, in _get_layout
    clean_line, self._fontproperties, ismath=ismath)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "/home/tommy/lisaenv/lib/python3.6/site-packages/matplotlib/texmanager.py", line 317, in _run_checked_subprocess
    exc=exc.output.decode('utf-8'))) from exc
RuntimeError: latex was not able to process the following string:
b'$\\\\log_{10} (\\\\Omega_0) = 1.24 \\\\times 10^{-6} ^{+0.0001}_{--0.0000}$'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/home/tommy/.cache/matplotlib/tex.cache/0dfca64bb48e87b7cdbc55a9f95e977e.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/utf8.def
(/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ot1enc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/omsenc.dfu)
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file 0dfca64bb48e87b7cdbc55a9f95e977e.aux.
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Double superscript.
l.14 ...og_{10} (\Omega_0) = 1.24 \times 10^{-6} ^
                                                  {+0.0001}_{--0.0000}$}
No pages of output.
Transcript written on 0dfca64bb48e87b7cdbc55a9f95e977e.log.
'''

**Comment by kuan0020** [comment]
Also, for the Bayes' factor plot, can you send me Alexander's plot for reference? Thanks.

**Comment by sharanbngr** [comment]
> Hey @sharanbngr
> 
> I think by adding this code below
> 
> > post = np.loadtxt(params['out_dir'] + "/post_samples.txt")
> 
> in plotmaker.py will generate a corner plot for Omega0 instead of log10Omega0. Let me know if it's right!
> 
> ### Change Omega0 from "log10 Omega" back to normal
> ```
> for x in range(len(post)):
>     post[x][1] = np.power(10,post[x][1])
> ```

I think that is correct. However you can get much better performance by vectorizing, which in principle is always better than for loops. You can vectorize this by doing 

`post[:, 1] = 10**(post[:, 1])`

**Comment by sharanbngr** [comment]
> label =  parameters[ii][:-1] + ' = ' + mean_form + '^{+' + err[0] + '}_{-' + err[1] + '}$'

I think for now if you comment out the following line it should work. We can figure out a better workaround latter. 

`label =  parameters[ii][:-1] + ' = ' + mean_form + '^{+' + err[0] + '}_{-' + err[1] + '}$'`

**Comment by sharanbngr** [comment]
> Also, for the Bayes' factor plot:
> 
> 1. Do I plot logZ(orbiting)/logZ(stationary) or Z(orbiting)/Z(stationary)?
> 2. For the error bar, is it logZ or Z, and is it also the ratio of Zerr(orbiting)/Zerr(stationary)?
> 3. Can you send me Alexander's plot for reference? Thanks.

1. Its  Z(orbiting)/Z(stationary) or equivalently log(Zorbiting - Zstationary)
2. I think you should propagate the errors in both into the bayesfactor. 
3. Emailed you

**Comment by kuan0020** [comment]
For the bayesfactor plot, is the x axis the random seed number?

**Comment by sharanbngr** [comment]
> For the bayesfactor plot, is the x axis the random seed number?

Thats correct

**Comment by kuan0020** [comment]
Hey @sharanbngr 

I tried to compute Baye's factor using this equation
```
bayes_factor = 10**(logz_o - logz_s)
```
but logz_o - logz_s is in the range of a 10^2, this results to an extremely large number that python calls it inf, is there any trick to go around this? Or I should change the equation to another form? I can't seem to go around this.

**Comment by kuan0020** [comment]
I fixed the inf problem by adding:
```logz_o = np.array(logz_o, dtype=np.float128)```
Thanks.

**Comment by kuan0020** [comment]
Hey @sharanbngr ,
From Alexander's plot, I can see that his bayes' factor is in the range of 10^2, but the bayes' factor I get is extremely huge. 
This is the formula I used to compute it, did I make a mistake?
```bayes_factor = 10**(logz_o - logz_s)
```

**Comment by kuan0020** [comment]
Hey @sharanbngr, is it logical to have logz(orbiting) < than logz(stationary)? Even with Alexander's params I still get a very large number, I've decided to plot log(z_orbiting/z_stationary, which is equivalent to log(z_orbiting) - log(z_stationary). Though, logz_o - logz_s will give a negative number because of logz_o < logz_s, do I have to worry about that? Or that's a result I can expect as well. 

I will post the params I use in another comment below.

**Comment by kuan0020** [comment]
```
[params]
fmin=1e-4
fmax=1e-2
## duration in seconds, should be compatiable with fmin
duration=5e6
## segment length for fft in seconds, should be compatiable with fmin
## Note by SB: Looks like this needs to be atleast a factor of 10 larger than 1/fmin
## to give consistant recoveries.
seglen=5e4
## sample rate in Hz, should be compatible with fmax
## Note by SB: Looks like this needs to be atleast a factor of 4
## higher than fmax (as opposed to the usual factor of 2) to give
## consistent recoveries.
fs=0.25
Shfile=LISA_2017_PSD_M.npy
nside=4

## LISA configuration. Can be stationary or orbiting
lisa_config=orbiting

## Level of the tdi. Can be michelson, xyz or aet
tdi_lev=aet

# If the mldc flag is set to 1, then the time series data is read in from a file.
mldc=0
datafile=SGWB_withnoise_full.txt

## Current options: SGWB_withnoise_full.txt mldc_tdi_withnoise.txt

## If loadResponse is true, then a previously generated set of detector responses is read in from a file. Only use when running repeated analyses on the same data set. Only used for orbiting LISA configuration due to the increased computation time of that case.
## File loaded depends on tdi_lev.
loadResponse=0

## If loadCustom is also true, the detector response arrays will be loaded from files specified by the user (responsefile1,2,3). Specified detector responses should be compatible with tdi_lev.
## IMPORTANT - only load responses when analyzing the dataset originally used to generate them. The code will throw an error if the duration/segment length (dur/seglen) don't match. However, mismatched combinations of data and responses can still function in some cases and will produce erroneous results.
loadCustom=0
responsefile1=R1arrayAETMLDC.txt
responsefile2=R2arrayAETMLDC.txt
responsefile3=R3arrayAETMLDC.txt

## fref parameter useful for powerlaw stochastic backgrounds
fref = 25
## recovery model type, can be isgwb, sph_sgwb, isgwb_only or noise_only for now
modeltype=isgwb
lmax=0
## Truevals for whatever parameters are being used.
## This should be a comma seperate list WITHOUT spaces
## For sph, the list is alpha, {log_omega_lm}, Np, Na
truevals=0.667,-8.455,-41.045,-48.443


[inj]
# Power Law Injection
# Omege0 is defined as the power at 1e-3 Hz
doInj=1
omega0=4.5e-9
alpha=0.667
Np=9e-42
Na=3.6e-49
injtype=isgwb

[run_params] # Parameters related to the run or to the sampler
out_dir=./o_n4_s50
verbose=1
# Set doPreProc to 1 to force generation of fake data again rather than used
# precalculated data in the data_spectrum file
doPreProc=0
nlive=500
Nthreads=1
## If FixSeed is true, the sampler will use random states generated by the seed given in the 'seed' parameter below. This allows for reproduction of sampling results; for a given seed value, repeated analyses of the same dataset will produce precisely identical results. The seed can be any unsigned 32-bit integer.
FixSeed=1
seed=50
# Must be .npz file
input_spectrum=data_spectrum.npz

```

**Comment by sharanbngr** [comment]
> Hey @sharanbngr, is it logical to have logz(orbiting) < than logz(stationary)? Even with Alexander's params I still get a very large number, I've decided to plot log(z_orbiting/z_stationary, which is equivalent to log(z_orbiting) - log(z_stationary). Though, logz_o - logz_s will give a negative number because of logz_o < logz_s, do I have to worry about that? Or that's a result I can expect as well.
> 
> I will post the params I use in another comment below.

I thought yesterday we were seeing runs with logz_o >logz_s. Is this with a higher nside?

**Comment by kuan0020** [comment]
> > Hey @sharanbngr, is it logical to have logz(orbiting) < than logz(stationary)? Even with Alexander's params I still get a very large number, I've decided to plot log(z_orbiting/z_stationary, which is equivalent to log(z_orbiting) - log(z_stationary). Though, logz_o - logz_s will give a negative number because of logz_o < logz_s, do I have to worry about that? Or that's a result I can expect as well.
> > I will post the params I use in another comment below.
> 
> I thought yesterday we were seeing runs with logz_o >logz_s. Is this with a higher nside?

Yes, yesterday's result is logz_o > logz_s. After changing params to Alexander's, the logz switched. This is with nside=4, which is the same as before.

**Comment by sharanbngr** [comment]
> > > Hey @sharanbngr, is it logical to have logz(orbiting) < than logz(stationary)? Even with Alexander's params I still get a very large number, I've decided to plot log(z_orbiting/z_stationary, which is equivalent to log(z_orbiting) - log(z_stationary). Though, logz_o - logz_s will give a negative number because of logz_o < logz_s, do I have to worry about that? Or that's a result I can expect as well.
> > > I will post the params I use in another comment below.
> > 
> > 
> > I thought yesterday we were seeing runs with logz_o >logz_s. Is this with a higher nside?
> 
> Yes, yesterday's result is logz_o > logz_s. After changing params to Alexander's, the logz switched. This is with nside=4, which is the same as before.

In that case, it's fine. Go ahead and make the bayesfactor plots and we will think about how to interpret them when we meet on Friday.

**Comment by kuan0020** [comment]
Ok, I will do the bayesfactor plots in log_10, if so, I cannot think of a way to compute the uncertainty in log_10(Zo/Zs) because the error propagation formula requires the actual Zo and Zs values to compute. Should I just approximate the uncertainties? Or I just plot the bayesfactor plots without it for now, then we discuss more on Friday? I am almost done with running the orbiting/stationary analysis for both nside=4 & 8.

**Comment by kuan0020** [comment]
Hey @sharanbngr , just a quick clarification, do you run run_blip.py in python or python3 ? I'm thinking that might be the cause of the problem I'm facing.

**Comment by sharanbngr** [comment]
@kuan0020 Sorry about the late reply. I run with python3 but afaik it shouldn't change based on what you have used. Are you sourcing the virtualenv? If you are both python and python3 should be the same thing.

**Comment by kuan0020** [comment]
https://docs.google.com/presentation/d/1uuhY1vxJdz5bgdTFGf_aNqXFacbAgLIkde1D5BlHfA4/edit?usp=sharing

**Comment by kuan0020** [comment]
https://docs.google.com/presentation/d/1uuhY1vxJdz5bgdTFGf_aNqXFacbAgLIkde1D5BlHfA4/edit?usp=sharing

**Comment by kuan0020** [comment]
> https://docs.google.com/presentation/d/1uuhY1vxJdz5bgdTFGf_aNqXFacbAgLIkde1D5BlHfA4/edit?usp=sharing

There's an update to the graph, I missed out something in the code that made the data weird. Now it is ready.

**Comment by sharanbngr** [comment]
- [ ] Reproduce MLDC based bayesfactor plots for different seeds

 - [ ] Fix our own simulated data-set to understand the source of the statistical fluctuations.  

 - [ ] repeat runs with our own fixed data set for different seeds

**Comment by kuan0020** [comment]
![own3_2](https://user-images.githubusercontent.com/60793092/76653661-1e0d0d80-6537-11ea-9c2e-5c94d7a7abb0.png)
