### ISSUE TITLE
Bayesfactor randomness bug

### ISSUE THREAD

**Issue by sharanbngr** [sharanbngr/blip#39]
Diagnostic analysis for fixing the Bayesfactor bug

-   Replicate the mldc analysis with the new version of the code
- [ ] Checkbox for for Alexander 
- [x] Checkbox for for Tommy

- [x] Issue for Sharan : Add a **separate** random seed for the signal gen

- [x] Issue for Tommy : Redo the Bayesfactor plots with a single data set of our generation.

**Comment by kuan0020** [comment]
Hey @criswellalexander , what was the nside you used to analyze the mldc data? I think the params file you sent me is an older version. Perhaps you guys had a fixed nside back then. Also, for the parameters you used, it had a fmax of 1e-2 and duration of 5e7, these settings took me more than 1.5 hours to diagnose the mldc data. Do you think we can come to a different parameters from your old params, and we stick to a new common params that can allow us to diagnose faster?

**Comment by criswellalexander** [comment]
A couple things:
When running over the MLDC data, you will not need to specify a nside value; that is something solely used for our own data generation. The MLDC data is an independent data set created by some of our collaborators in LISA as part of a broader data analysis challenge.

The length of the MLDC data is what's causing the long analysis time here. I'd prefer to run over the entire dataset, which I would be that 5e7 value. Honestly, it's a credit to Sharan's refactoring and vectorizing of the code that it only took an hour and a half; when I ran over the full dataset to report our results to the MLDC folks, it took considerably longer!
I'd also rather we kept the same parameters overall, in order to make sure that any differences we're seeing stem from the code change as opposed to a different analysis approach. At some point, though, I would like to see what effect changing fmax has on the results.

**Comment by sharanbngr** [comment]
@kuan0020 @criswellalexander 

> When running over the MLDC data, you will not need to specify a nside value; that is something solely used for our own data generation. The MLDC data is an independent data set created by some of our collaborators in LISA as part of a broader data analysis challenge.

Actually that is not true anymore. Even during recovery we need a grid to measure antenna patterns and I have moved all that code to use Healpix for consistency (rather than the adhoc grid we were using before.  And the same nside value is used for both simulation and recovery. 

This actually raises an imp. point which I hadn't appreciated before; that we might be seeing effects of not just small nside in simulation but also a small nside during recovery. In other words we have to figure out what are optimal values of nside to use for simulation and recovery.  

With the MLDC data I would suggest to check if the scatter reduces as we up nside (4, 8, 12, 16, 20).

To control for that when creating our own data set it might be useful to do so with a large value of nside (say 20-30) and then when recovery testing with different values of nside. My apologies, this is a complication that I didn't realize earlier.

**Comment by kuan0020** [comment]
By the way @sharanbngr , I tried to generate our own data by using np.savetxt() method and I get an error saying the size of the data does not match. I checked, and I noticed that all three h1.h2 and h3 have the same length, but the timearray has a different length and it caused np.savetxt() to fail. Should timearray have the same length as h1,2,3? What should I do next?

**Comment by sharanbngr** [comment]
> By the way @sharanbngr , I tried to generate our own data by using np.savetxt() method and I get an error saying the size of the data does not match. I checked, and I noticed that all three h1.h2 and h3 have the same length, but the timearray has a different length and it caused np.savetxt() to fail. Should timearray have the same length as h1,2,3? What should I do next?

@kuan0020  Change line 73 in run_blip.py to 

`self.timearray = times[0:N]`

**Comment by kuan0020** [comment]
>With the MLDC data I would suggest to check if the scatter reduces as we up nside (4, 8, 12, 16, 20).

![nsideComparisons](https://user-images.githubusercontent.com/60793092/76050989-f7dfe000-5f2e-11ea-99e8-a1dd260a46cc.png)

**Comment by sharanbngr** [comment]
> > With the MLDC data I would suggest to check if the scatter reduces as we up nside (4, 8, 12, 16, 20).
> 
> ![nsideComparisons](https://user-images.githubusercontent.com/60793092/76050989-f7dfe000-5f2e-11ea-99e8-a1dd260a46cc.png)

Wow, this looks surprisingly good! So the takeaway is that when we switch to using healpix with recovery maps it fixes the bias in the MLDC?

**Comment by kuan0020** [comment]
I guess. With this graph, which nside should I use for different random seeds analysis for the MLDC data, since the bayes' factor is roughly the same for all nsides, can I just pick any?

**Comment by sharanbngr** [comment]
> I guess. With this graph, which nside should I use for different random seeds analysis for the MLDC data, since the bayes' factor is roughly the same for all nsides, can I just pick any?

Maybe try the lowest and the highest values we have used : 4 and 20 to check on either ends of the spectrum. 

PS: You haven't been seeing any trouble like yesterday with the MLDC data?

**Comment by kuan0020** [comment]
I didn't have any problem analyzing MLDC data. I had problems analyzing ownData2.txt but that's fixed by setting the duration to 5e5 or lesser. I see that you pushed an updated version of the code, what should I do to pull it?

**Comment by kuan0020** [comment]
This is the corners plot for stationary case with our new own3data.txt. It took my laptop a LOOOOONG time to finish analyzing it. 
![corners](https://user-images.githubusercontent.com/60793092/76148084-6b393d00-6068-11ea-942b-75cee734a264.png)

I am currently doing the orbiting case now, and its been almost an hour, it is still calculating fourier spectra. Is the newly updated run_blip compatible with orbiting case?

**Comment by kuan0020** [comment]
I think the newly updated run_blip (Mar 6 update) is messing up the analysis on MLDC data. I tried to do the analysis for MLDC data with nside=4 and with 6 different seeds, when I do the analysis for seed=10, run_blip gave a different result depending on which code I used. 

This is the corners plot before Mar 6 update:
![corners](https://user-images.githubusercontent.com/60793092/76658263-be682f80-6541-11ea-82f1-6338a7137365.png)

This is the corners plot after Mar 6 update, with the same params:
![corners](https://user-images.githubusercontent.com/60793092/76658293-ca53f180-6541-11ea-9c34-8f9b624185ba.png)

**Comment by sharanbngr** [comment]
Hi @kuan0020. From my email: 

> 3) This issue was causing the problem with the diag_psd plots and the completely wrong recoveries when reading our own data through a text file. Essentially there are two equivalent ways you can think of gravitational-wave data : as strain or as doppler tracking data. Our code represents gravitational-wave data as strain, but the mldc uses doppler tracking. So when data was read in though the mldc flag the code assumes the data is doppler and converts it to strain. But when we store data in a text file it is already strain data. So to stop this, when reading our own data though the mldc flag you need to comment out line 114 of run_blip.py which is where the conversion is taking please. 
> 
>   self.r1, self.r2, self.r3 = self.r1/(4*self.f0.reshape(self.f0.size, 1)), self.r2/(4*self.f0.reshape(self.f0.size, 1)), self.r3/(4*self.f0.reshape(self.f0.size, 1))
> 
> You still this it *uncommented* when using the mldc data. We will figure out a better fix like a flag later. The good news is however should have nothing to do with the bayesfactor scatter we are seeing. 


Did you uncomment the line again when running with MLDC data? (I will add a flag for it today, I promise)

**Comment by kuan0020** [comment]
Omg, yes, I forgot that MLDC data needs to be converted into strain data. My bad, I am running the analysis again with this line uncommented. Thanks @sharanbngr.

**Comment by kuan0020** [comment]
> (I will add a flag for it today, I promise)

Actually if you don't mind, I'd like to try to add a param option to enable doppler and strain data conversion, you can leave that to me for now, if I fail I will ask you again haha

**Comment by sharanbngr** [comment]
> > (I will add a flag for it today, I promise)
> 
> Hey @sharanbngr ,
> Actually if you don't mind, I'd like to try to add a param option to enable doppler and strain data conversion, you can leave that to me for now, if I fail I will ask you again haha

No, Go for it :)

**Comment by kuan0020** [comment]
This is what I got for different seeds using MLDC data.

![bf_mldc_seeds](https://user-images.githubusercontent.com/60793092/76684986-34ba6f80-65de-11ea-8a3d-518f09daca13.png)

**Comment by criswellalexander** [comment]
Say Tommy, is that y-axis Bayes factor or log Bayes factor? If it's log, that's very reminiscent of what I was getting before.

**Comment by kuan0020** [comment]
[Z.txt](https://github.com/sharanbngr/blip/files/4333061/Z.txt)

This file contains the information for the evidences. Also, @criswellalexander , the y-axis is the actual Bayes factor. Somehow our data does not have the same range of bayes factor. But my data makes sense too, since the baye's factor should not be affected by random seed#, and the errorbars overlap each other in my analysis.

**Comment by criswellalexander** [comment]
Huh, interesting. Thank you!

Alexander Criswell
PhD Student, Astrophysics | Minnesota Institute for Astrophysics

**Comment by sharanbngr** [comment]
> This is what I got for different seeds using MLDC data.
> 
> ![bf_mldc_seeds](https://user-images.githubusercontent.com/60793092/76684986-34ba6f80-65de-11ea-8a3d-518f09daca13.png)

Interesting! These recoveries look like they are fairly unbiased. What’s the nside used here?

**Comment by kuan0020** [comment]
nside = 4, should I do another one with different nside?

**Comment by sharanbngr** [comment]
> nside = 4, should I do another one with different nside?

Yeah, might be useful. Something like nside =12, 16
