### ISSUE TITLE
cg makeLISAdata line 503

### ISSUE THREAD

**Issue by kuan0020** [sharanbngr/blip#53]
```
            if ii == 0:
                # Take inverse fft to get time series data
                h1 = splice_win * np.fft.irfft(htilda1, N)
                h2 = splice_win * np.fft.irfft(htilda2, N)
                h3 = splice_win * np.fft.irfft(htilda3, N)

            else:

                ## First append half-splice worth of zeros
                h1 = np.append(h1, np.zeros(halfN))
                h2 = np.append(h2, np.zeros(halfN))
                h3 = np.append(h3, np.zeros(halfN))
```

The else block referenced h1 before assignment. I'm getting this referenced before assignment error, because the primordial model falls into the else block.

**Comment by sharanbngr** [comment]
@kuan0020 You should not get an error here. The index `ii` is a reference to the time index. You always start with `ii=0`

**Comment by kuan0020** [comment]
> @kuan0020 You should not get an error here. The index `ii` is a reference to the time index. You always start with `ii=0`

You are right. It was outside of the loop, that's why it didn't go through `ii=0`.
